
import "./globals.css";
import Navbar from './components/Navbar';


export const metadata = {
  title: "Perplora Ai | AI Service Provider",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
    
        {children}
      </body>
    </html>
  );
}
